### ISSUE TITLE
Does this code utilize Cudnn?

### ISSUE THREAD

**Issue by EhsanEI** [layumi/2015_Face_Detection#10]
Hi,
Thanks for this amazing code.
I'm trying to detect faces in some images. The results are surprisingly accurate. I'm just wondering if I can improve its speed on my machine.
I've compiled matconvnet with gpu without Cudnn (My graphics card doesn't support Cudnn). Now the code takes ~5 seconds on each test image and there's a heavy load on my CPU while running the code. There's almost no difference in the performance when I compile matconvnet with CPU.
I don't know if the reason for this lack of speed is that I'm not using Cudnn (so I can buy a newer card with Cudnn support) or is it because of the computational load on CPU.

**Comment by layumi** [comment]
@EhsanEI 
You can use "tic" "toc" in matlab to record time. As far as I test my code, the processing of getting patch from original pic is slow. Forward processing don't take so much time. ( So gpu does't play a big role and cudnn is not necessary either)  You can find that I use mex file to accelerate the IO speed but it might be still considered as too slow.
